### ISSUE TITLE
Plan of what I'm working on currently

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#372]
- [ ] Tooltips #78 
- [ ] Macros #75 
- [x] Rewriting RPC 
  - [x] #318 
  - [x] #306
- [ ] Active Modules color #28 
- [ ] AutoExp durability #242 
  - [x] works
  - [ ] taking a piece of armour off breaks it
- [ ] Timer #33
- [ ] Fix lag with having lots of friends #379 
- [ ] EntityStats find username #282 
- [ ] Create a method for looking up UUID #380 
- [x] Speed for info module #42 
- [ ] Optimize Cape loading #359 
- [x] Surround AutoCenter #382 
- [ ] Check if this works #317 
- [ ] Scaffold spoof crouch #386
- [x] Freecam broke #292
- [ ] GUI Proper Menus #392

**Comment by S-B99** [comment]
Updated.

**Comment by S-B99** [comment]
Updated.

**Comment by S-B99** [comment]
Updated.

**Comment by S-B99** [comment]
Updated

**Comment by S-B99** [comment]
Updated.

**Comment by S-B99** [comment]
Updated.

**Comment by S-B99** [comment]
Updated.

**Comment by Vonr** [comment]
should have fixed the armor thing

**Comment by S-B99** [comment]
i reverted your commit and fucked around. you fixed the crash but made the threshold check break, which is worse then crashing since we already had it working without a threshold check

**Comment by Vonr** [comment]
ill look around since i did it without an ide

**Comment by S-B99** [comment]
no i fixed your changes syntax locally

**Comment by S-B99** [comment]
they just didn't work after

**Comment by S-B99** [comment]
i tried separating it and discovered the method to check threshold never runs

**Comment by Vonr** [comment]
yeah ill fuck around with that

**Comment by Vonr** [comment]
also
intellij run config pls

**Comment by S-B99** [comment]
what about that. it works for me

**Comment by Vonr** [comment]
need your config it doesnt work for me

**Comment by S-B99** [comment]
what config aaaaaa

**Comment by Vonr** [comment]
intellij runclient config

**Comment by S-B99** [comment]
check discord aaaa

**Comment by S-B99** [comment]
Updated. Closed #42.

**Comment by S-B99** [comment]
Moved to a projects board
